### PR TITLE
Add a rubocop channel to the codeclimate config

### PR DESCRIPTION
**Pull request by djberg96**
Add a rubocop channel to the codeclimate config

### CODE REVIEW

**Comment by carbonin** [comment]
Is this supposed to fix the issue with codeclimate or are we missing something still in this repo?

**Comment by djberg96** [comment]
@carbonin Yeah, it was supposed to fix it. Not sure why some of the repos are reaching for rubocop 0.52, though.

**Comment by carbonin** [comment]
> Not sure why some of the repos are reaching for rubocop 0.52, though.

Looks like this PR bundled 0.72.0 so that's not the problem.
https://travis-ci.org/ManageIQ/manageiq-appliance_console/jobs/555747952#L375

**Comment by carbonin** [comment]
Do we need to add `rubocop-performance` somewhere?

**Comment by djberg96** [comment]
@carbonin shouldn't have to, didn't have to for the others. Should be pulled in from the manageiq-content parent, which was updated at https://github.com/ManageIQ/guides/pull/353

**Comment by djberg96** [comment]
@carbonin This is actually a function of the way codeclimate works. If you look at the details of the failure, you'll see it's actually pointing at 0dd3bcf9.

You can that the build for this PR is https://codeclimate.com/github/ManageIQ/manageiq-appliance_console/builds/772, which is green.

I've forwarded you a message from the codeclimate support team that I hope clears things up.

Anyway, you can merge this. :)

**Pull request merged**
